modLoader="javafml"
loaderVersion="[28,)"

issueTrackerURL="https://github.com/BoogieMonster1O1/NoCavesNoRavines/issues"

[[mods]]
	modId="nocavesnoravines"
	version="1.1.1"
	displayName="No Caves No Ravines"
	displayURL="https://www.curseforge.com/minecraft/mc-mods/nocavesnoravines"
	credits="BoogieMonster1O1"
	authors="Matthias Mann"
	description='''
	Disables caves and ravines
	'''

[[dependencies.nocavesnoravines]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[28,)" #mandatory
    ordering="NONE"
    side="BOTH"
    
[[dependencies.nocavesnoravines]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
